install:
  - choco install ghc -version 7.10.3
  - SET PATH=%PATH%;C:\tools\ghc\ghc-7.10.3\bin
  - curl -o cabal.tar.gz https://www.haskell.org/cabal/release/cabal-install-1.20.0.3/cabal-1.20.0.3-i386-unknown-mingw32.tar.gz
  - 7z x cabal.tar.gz
  - 7z x cabal.tar
  - ren cabal*.exe cabal.exe
  - cabal update -v3

build_script:
  - cd Cabal
  - ghc --make -threaded -i -i. Setup.hs
  - ..\cabal install --only-dependencies --enable-tests
  - Setup configure --user --ghc-option=-Werror --enable-tests
  - Setup build
  - Setup test --show-details=streaming
  - Setup install
  - cd ..\cabal-install
  - ghc --make -threaded -i -i. Setup.hs
  - ..\cabal install --only-dependencies --enable-tests
  - Setup configure --user --ghc-option=-Werror --enable-tests
  - Setup build
  - Setup test --show-details=streaming
