branches:
  only:
    - appveyor

install:
  - choco install ghc -version 7.10.3
  - SET PATH=%PATH%;C:\tools\ghc\ghc-7.10.3\bin
  - curl -o cabal.7z http://wordroute.com/grayjay/cabal.7z
  - 7z x cabal.7z
  - cabal update -v3

build_script:
  - cd Cabal
  - ghc --make -threaded -i -i. Setup.hs
  - ..\cabal sandbox init
  - ..\cabal install --only-dependencies --enable-tests
  - Setup configure --package-db=.cabal-sandbox\x86_64-windows-ghc-7.10.3-packages.conf.d --ghc-option=-Werror --enable-tests
  - Setup build
  - Setup test --show-details=streaming
  - cd ..\cabal-install
  - ghc --make -threaded -i -i. Setup.hs
  - ..\cabal sandbox init
  - ..\cabal add-source ..\Cabal
  - ..\cabal install --only-dependencies --enable-tests
  - Setup configure --package-db=.cabal-sandbox\x86_64-windows-ghc-7.10.3-packages.conf.d --ghc-option=-Werror --enable-tests
  - Setup build
  - Setup test --show-details=streaming
