branches:
  only:
    - appveyor

install:
  - choco install ghc -version 7.6.3
  - SET PATH=%PATH%;C:\tools\ghc\ghc-7.6.3\bin
  - curl -o cabal.tar.gz https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-i386-unknown-mingw32.tar.gz
  - 7z x cabal.tar.gz
  - 7z x cabal.tar
  - ren cabal*.exe cabal.exe
  - curl -X GET http://hackage.haskell.org/packages/archive/00-index.tar.gz -v3 -L -o 00-index.tar.gz
  - cabal update -v3

build_script:
  - cd Cabal
  - ghc --make -threaded -i -i. Setup.hs
  - ..\cabal sandbox init
  - ..\cabal install --only-dependencies --enable-tests
  - Setup configure --package-db=.cabal-sandbox\x86_64-windows-ghc-7.6.3-packages.conf.d --ghc-option=-Werror --enable-tests
  - Setup build
  - Setup test --show-details=streaming
  - cd ..\cabal-install
  - ghc --make -threaded -i -i. Setup.hs
  - ..\cabal sandbox init
  - ..\cabal add-source ..\Cabal
  - ..\cabal install --only-dependencies --enable-tests
  - Setup configure --package-db=.cabal-sandbox\x86_64-windows-ghc-7.6.3-packages.conf.d --ghc-option=-Werror --enable-tests
  - Setup build
  - Setup test --show-details=streaming
