branches:
  only:
    - appveyor

install:
  - choco install HaskellPlatform -version 2013.2.0.0
  - SET PATH=%PATH%;C:\tools\"Haskell Platform"\2013.2.0.0\bin
  - cabal update -v3

build_script:
  - cd Cabal
  - ghc --make -threaded -i -i. Setup.hs
  - cabal sandbox init
  - cabal install --only-dependencies --enable-tests
  - Setup configure --package-db=.cabal-sandbox\x86_64-windows-ghc-7.6.3-packages.conf.d --ghc-option=-Werror --enable-tests
  - Setup build
  - Setup test --show-details=streaming
  - cd ..\cabal-install
  - ghc --make -threaded -i -i. Setup.hs
  - cabal sandbox init
  - cabal add-source ..\Cabal
  - cabal install --only-dependencies --enable-tests
  - Setup configure --package-db=.cabal-sandbox\x86_64-windows-ghc-7.6.3-packages.conf.d --ghc-option=-Werror --enable-tests
  - Setup build
  - Setup test --show-details=streaming
