install:
  - choco install HaskellPlatform -version 2014.2.0.0
  - SET PATH=%APPDATA%\cabal\bin;C:\Program Files\Haskell Platform\2014.2.0.0\bin;C:\Program Files\Haskell Platform\2014.2.0.0\mingw\bin;C:\Program Files\Haskell Platform\2014.2.0.0\lib\extralibs\bin;%PATH%
  - cabal update
  - cabal --version
  - cabal install cabal-install
  - cabal --version

build_script:
  - cd Cabal
  - ghc --make -threaded -i -i. Setup.hs
  - cabal sandbox init
  - echo "" | cabal install --only-dependencies --enable-tests
  - Setup configure --package-db=.cabal-sandbox\x86_64-windows-ghc-7.8.3-packages.conf.d --ghc-option=-Werror --enable-tests
  - Setup build
  - Setup test unit-tests --show-details=streaming
  - Setup install
  - cd ..\cabal-install
  - ghc --make -threaded -i -i. Setup.hs
  - cabal sandbox init
  - cabal add-source ..\Cabal
  - echo "" | cabal install --only-dependencies --enable-tests
  - Setup configure --package-db=.cabal-sandbox\x86_64-windows-ghc-7.8.3-packages.conf.d --ghc-option=-Werror --enable-tests
  - Setup build
  - Setup test --show-details=streaming
