branches:
  only:
    - appveyor

install:
  - choco install ghc -version 7.6.3
  - SET PATH=%PATH%;C:\tools\ghc\ghc-7.6.3\bin

build_script:
  - cd Cabal
  - ghc --make -threaded -i -i. Setup.hs
  - Setup configure
  - Setup build
