install:
  - choco install ghc -version 7.10.3
  - SET PATH=%PATH%;C:\tools\ghc\ghc-7.10.3\bin
  - curl -o cabal.zip https://www.haskell.org/cabal/release/cabal-install-1.24.0.0-rc1/cabal-install-1.24.0.0-rc1-x86_64-unknown-mingw32.zip
  - 7z x cabal.zip
  - cabal --version
  - cabal update

build_script:
  - cd cabal-install
  - cabal sandbox init
  - cabal sandbox add-source ..\Cabal
  - echo "" | ..\cabal install --only-dependencies
  - echo "" | ..\cabal --ignore-sandbox install process-1.4.2.0
  - ..\cabal configure
  - ..\cabal build
  - ..\cabal test
